// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniatureMadness.Data;

namespace MiniatureMadness.Migrations.StoreDB
{
    [DbContext(typeof(StoreDBContext))]
    [Migration("20200425223547_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MiniatureMadness.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "This coffee cake inspired cupcake is light and testes of sweet almonds and oats",
                            Image = "/Assets/CanvaAlmond.jpg",
                            Name = "Oats & Almond",
                            Price = 3m,
                            Sku = "153-785"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Sharp clean raspberry mixes with a deep dark chocolate in this mini cupcake",
                            Image = "/Assets/CanvaChocoCupcake.jpg",
                            Name = "Chocolate Raspberry",
                            Price = 2m,
                            Sku = "597-416"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Wheather doing a gender reveal or a simple baby shower these vanilla cupcakes are topped with sweet marzipan decorations",
                            Image = "/Assets/CanvaBabyShower.jpg",
                            Name = "Baby Shower Special",
                            Price = 4m,
                            Sku = "984-354"
                        },
                        new
                        {
                            ID = 4,
                            Description = "A simple and sweet milk chocolate cupcake topped with chocolate frosting and a sprinkle of sea salt",
                            Image = "/Assets/CanvaChocolate.jpg",
                            Name = "Classic Chocolate",
                            Price = 2m,
                            Sku = "358-469"
                        },
                        new
                        {
                            ID = 5,
                            Description = "A new take on red velvet, this is a soft chocolate flavored cupcake colored with current and current jam is added in the frosting for a truely blissful experiance",
                            Image = "Assets/CanvaCurrent.jpg",
                            Name = "Current",
                            Price = 3m,
                            Sku = "163-541"
                        },
                        new
                        {
                            ID = 6,
                            Description = "These soft vanilla cupcakes are flavored with slightly tart blueberries which make them so refreshing",
                            Image = "Assets/CanvaFourCupcakes.jpg",
                            Name = "Blueberry bliss",
                            Price = 3m,
                            Sku = "268-198"
                        },
                        new
                        {
                            ID = 7,
                            Description = "These are a mixture of sweet vanilla and strawberry. Topped with candy hearts",
                            Image = "/Assets/CanvaHearts.jpg",
                            Name = "Sweet heart",
                            Price = 2m,
                            Sku = "698-164"
                        },
                        new
                        {
                            ID = 8,
                            Description = "Sweet soft mint paired with deep dark chocolate",
                            Image = "/Assets/CanvaMintchoco.jpg",
                            Name = "Mint and chocolate",
                            Price = 2m,
                            Sku = "354-925"
                        },
                        new
                        {
                            ID = 9,
                            Description = "This is made with purple sweet potatoe to add a delicate flavor that is soft and slightly sweet",
                            Image = "/Assets/CanvaPurpleCupcake.jpg",
                            Name = "Purple princess",
                            Price = 3m,
                            Sku = "567-298"
                        },
                        new
                        {
                            ID = 10,
                            Description = "These multi colored cupcakes come in vanilla with a touch of magic",
                            Image = "/Assets/CanvaUnicornCupcakes.jpg",
                            Name = "Unicorn",
                            Price = 3m,
                            Sku = "364-975"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
