// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniatureMadness.Data;

namespace MiniatureMadness.Migrations.StoreDB
{
    [DbContext(typeof(StoreDBContext))]
    partial class StoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MiniatureMadness.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "The merc witht he mouth now in mini form",
                            Name = "Deapool",
                            Price = 1099m,
                            Sku = "153-785"
                        },
                        new
                        {
                            ID = 2,
                            Description = "The big green guy now can fit in your hand",
                            Name = "Hulk",
                            Price = 1199m,
                            Sku = "597-416"
                        },
                        new
                        {
                            ID = 3,
                            Description = "He is really good at shoting arrows, thats about it",
                            Name = "Hawk-eye",
                            Price = 499m,
                            Sku = "984-354"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Get to the bright side and look at all those happy little trees",
                            Name = "Bob Ross",
                            Price = 10000m,
                            Sku = "358-469"
                        },
                        new
                        {
                            ID = 5,
                            Description = "Destroy mini sized cities",
                            Name = "Godzilla",
                            Price = 999m,
                            Sku = "163-541"
                        },
                        new
                        {
                            ID = 6,
                            Description = "Get two and they can point at eachother",
                            Name = "Spiderman",
                            Price = 899m,
                            Sku = "268-198"
                        },
                        new
                        {
                            ID = 7,
                            Description = "He might change into a snake since you like them, but when you pick him up he changes back and stabs you",
                            Name = "Loki",
                            Price = 799m,
                            Sku = "698-164"
                        },
                        new
                        {
                            ID = 8,
                            Description = "maybe you have heard of him",
                            Name = "Starlord",
                            Price = 699m,
                            Sku = "354-925"
                        },
                        new
                        {
                            ID = 9,
                            Description = "to get eyes like his you need a to find a shady doctor in a max security prison... or just buy the mini",
                            Name = "Riddick",
                            Price = 799m,
                            Sku = "567-298"
                        },
                        new
                        {
                            ID = 10,
                            Description = "Comes with everything you need! Laptop, mouse, desk, slippers and coffee.",
                            Name = "Work at home mini set",
                            Price = 1100m,
                            Sku = "364-975"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
